### PR TITLE
display issues for “Delete add-on” button label (bug 1218414)

### PR DESCRIPTION
**Pull request by atiqueahmedziad**
https://bugzilla.mozilla.org/show_bug.cgi?id=1218414

### CODE REVIEW

**Comment by atiqueahmedziad** [comment]
@ngokevin r?

**Comment by atiqueahmedziad** [comment]
@ngokevin r?

**Comment by atiqueahmedziad** [comment]
updated
@ngokevin r?

**Comment by ngokevin** [comment]
thanks!

**Pull request merged**
