### PR TITLE
Adds reject action.

### PR DESCRIPTION
**Pull request by chuckharmston**
r? @ngokevin

### CODE REVIEW

**Comment by ngokevin** [comment]
r+.

perhaps in another PR, remove the addon from the store, or set its state to rejected. maybe a notification

**Comment by diox** [comment]
Note that the developer currently has no way of re-submitting his addon for review, as this was not defined in the walking skeleton.

**Comment by ngokevin** [comment]
well, besides resubmitting it from scratch

**Comment by diox** [comment]
Right. This is probably acceptable and I'm rewording the docs accordingly.

**Pull request merged**
