### PR TITLE
rm –rf MeOWs.

### PR DESCRIPTION
**Pull request by chuckharmston**
Lots of MOW-related code fattening our bundles and making greps more painful. Since nobody is using this for now, let's blow them out.

For posterity, they are preserved in a tag: https://github.com/mozilla/marketplace-content-tools/tree/websites_still_here

### CODE REVIEW

**Comment by chuckharmston** [comment]
r? @ngokevin

Probably missed some stuff, would appreciate a once-over to make sure I didn't.

**Comment by ngokevin** [comment]
hmm, i didn't mind them in there as they were contained within a directory. emotionally hesitant to blow out some nice code we spent a few weeks on...

**Comment by chuckharmston** [comment]
They're saved, and this commit can always be reverted. For now, they're just fattening our bundles. This is just under 2000 LOC we're blowing out.

**Comment by chuckharmston** [comment]
FWIW these failures are due to `AddonReviewDetail` and `AddonDashboardDetail`:

    TypeError: Cannot read property 'threads' of undefined

**Comment by ngokevin** [comment]
my bad, fixed the tests.

**Comment by chuckharmston** [comment]
Thanks, tests are passing now.

How do you feel about it overall? We'll slim down the bundles, clean up the code, make development on addons easier, and...realistically, nobody will ever actually use the MOW tools.

**Comment by ngokevin** [comment]
allow me a night of grieving and we can merge it.

**Comment by chuckharmston** [comment]
I'm going to yolo this so I can get #30 to rebase nicely.

**Pull request merged**
